//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamField.Model
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Animal
    {
        public int id { get; set; }
        public int herd_id { get; set; }
        public int responsible_user_id { get; set; }
        public string name { get; set; }
        public string sex_age_group { get; set; }
        public System.DateTime birth_datetime { get; set; }
        public System.DateTime receipt_datetime { get; set; }
        public float weight { get; set; }
        public float fatness { get; set; }
    
        public virtual Herd Herd { get; set; }
    }
}
