//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamField.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NormIndexLactating : NormIndexTaurus
    {
        public double Se { get; set; }
        public double ExchangeProtein { get; set; }
        public double AcidDetergentFiber { get; set; }
        public double NeutralDetergentFiber { get; set; }
        public double ExcahngeEnergyDryMatter { get; set; }
    }
}
