//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamField.Model
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class NormIndexGeneral
    {
        public long Id { get; set; }
        public float EnergyFeedUnit { get; set; }
        public float ExcahngeEnergy { get; set; }
        public float DryMatter { get; set; }
        public float RawProtein { get; set; }
        public float DigestibleProtein { get; set; }
        public float RawCellulose { get; set; }
        public float Salt { get; set; }
        public float Ca { get; set; }
        public float P { get; set; }
        public float Mg { get; set; }
        public float Fe { get; set; }
        public float Cu { get; set; }
        public float Zn { get; set; }
        public float Co { get; set; }
        public float Mn { get; set; }
        public float J { get; set; }
        public float Carotene { get; set; }
        public float VitaminD { get; set; }
        public float VitaminE { get; set; }
        public float VitaminA { get; set; }
    
        public virtual Ration Ration { get; set; }
    }
}
