//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamField.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NormIndexFatteing : NormIndexGeneral
    {
        public double ClevableProtein { get; set; }
        public double UnclevableProtein { get; set; }
        public double Starch { get; set; }
        public double Sugar { get; set; }
        public double RawFat { get; set; }
        public double K { get; set; }
        public double S { get; set; }
    }
}
