//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamField.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NormIndexFatteing : NormIndexGeneral
    {
        public float ClevableProtein { get; set; }
        public float UnclevableProtein { get; set; }
        public float Starch { get; set; }
        public float Sugar { get; set; }
        public float RawFat { get; set; }
        public float K { get; set; }
        public float S { get; set; }
    }
}
