//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamField.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NormIndexLactating : NormIndexTaurus
    {
        public float Se { get; set; }
        public float ExchangeProtein { get; set; }
        public float AcidDetergentFiber { get; set; }
        public float NeutralDetergentFiber { get; set; }
        public float ExcahngeEnergyDryMatter { get; set; }
        public float ExcangeProtein { get; set; }
    }
}
