//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamField.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RationFeed
    {
        public int ration_id { get; set; }
        public int feed_id { get; set; }
        public double amount { get; set; }
    
        public virtual Feed Feed { get; set; }
        public virtual Ration Ration { get; set; }
    }
}
